In [2]:
import numpy as np


In [18]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# get dimensioon
a.ndim

1

In [6]:
b.ndim

2

In [10]:
#get shape
a.shape


(3,)

In [9]:
b.shape

(2, 3)

In [20]:
#Get Type
a.dtype

dtype('int32')

In [19]:
#Get size
a.itemsize

4

In [26]:
#Get total size
a.itemsize * a.size

12

In [22]:
a.nbytes

12

In [23]:
b.dtype

dtype('float64')

In [27]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
#Get specific element [r,c]
print(a[1,5])
print(a[1,-2])

13
13


In [33]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [37]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [38]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [40]:
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [43]:
#3D EXAMPLE
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
#Get specific element (work outside in)
print(b[0,1,1])
print(b[:, 0, :])

4
[[1 2]
 [5 6]]


In [52]:
#replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing different types of arrays

In [59]:
#All 0s matrix
np.zeros(5)
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
#All 1s Matrix
np.ones((2,4), dtype = 'int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
#any other number
np.full((2,2),99, dtype='int16')

array([[99, 99],
       [99, 99]], dtype=int16)

In [65]:
#Any other number(full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
# random decimal numbers
np.random.rand(4,2)

array([[0.75023506, 0.38392228],
       [0.85543834, 0.08759179],
       [0.0699111 , 0.05038171],
       [0.26766475, 0.35461382]])

In [68]:
np.random.random_sample(a.shape)

array([[0.65821601, 0.72749956, 0.26102074, 0.36935215, 0.63708667,
        0.28732773, 0.34255868],
       [0.47291122, 0.21969475, 0.36318973, 0.35962539, 0.82981815,
        0.72273431, 0.95038544]])

In [72]:
# random integer values
np.random.randint(4,7, size = (3,3)) # 4=start value, 7=stop value

array([[6, 6, 4],
       [5, 5, 4],
       [6, 5, 4]])

In [74]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!!!!!

In [85]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a) #Note:a changes with b

[100   2   3]
[100   2   3]


In [88]:
# to prevent above error use copy method
a = np.array([1,2,3])
b = a.copy()
b[0] = 200
print(a)
print(b)

[1 2 3]
[200   2   3]


# Mathematics

In [89]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [90]:
a + 2

array([3, 4, 5, 6])

In [91]:
a - 2

array([-1,  0,  1,  2])

In [92]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [93]:
a * 2

array([2, 4, 6, 8])

In [95]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [96]:
a ** 2

array([ 1,  4,  9, 16])

In [97]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [98]:
#Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [101]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [103]:
#Finding Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [105]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.min(stats, axis = 1) # axis = 1 referes to rows and axis = 0 refers to columns

array([1, 4])

In [113]:
np.max(stats, axis = 1)

array([3, 6])

In [114]:
np.sum(stats)

21

# Reorganizing Arrays 

In [118]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

after2 = before.reshape((2,2,2))
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8]) #sizes of both arrays should be same

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
# Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Miscellaneous


Load data from file

In [9]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata.astype('int32') #prints in integer
filedata #prints in float

array([[  11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,
          89.],
       [ 234.,   78.,   67.,   59., 4098.,   56.,   77.,   88.,  567.,
        4567.],
       [4563., 7685., 9045.,   77., 1234.,  768., 7379.,  123.,  789.,
        6789.]])

Boolean Masking and Advanced Indexing

In [10]:
filedata>50

array([[False, False, False, False, False, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [11]:
filedata>=50

array([[False, False, False, False, False, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [12]:
filedata[filedata>=50]

array([  89.,  234.,   78.,   67.,   59., 4098.,   56.,   77.,   88.,
        567., 4567., 4563., 7685., 9045.,   77., 1234.,  768., 7379.,
        123.,  789., 6789.])

In [13]:
##You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [14]:
np.any(filedata > 50, axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [18]:
print(((filedata > 50) & (filedata < 100))

SyntaxError: incomplete input (3359474778.py, line 1)

In [21]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])